#!/bin/sh

ic=${1:-''}

jarfile='target/blackhole4d-1.11-SNAPSHOT-jar-with-dependencies.jar'
d=data
pydir='../../Python/BlackHole4dPython'

java -jar $jarfile <$ic >$d &
PID=$!
sleep 1
$pydir/filegraphics.py $d $ic&
wait $PID
set $(wc -l $d)
if [ $1 -gt 10000 ]
then
	$pydir/datachart.py $d $(($1 / 2000)) &
	$pydir/errorchart.py $d $(($1 / 2000)) &
else
	$pydir/datachart.py $d 1 &
	$pydir/errorchart.py $d 1 &
fi

